### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by zoechi** [davidmarne/built_redux_thunk#2]
I haven't used redux previously and 
have a hard time figuring out how to use the thunk middleware with built_redux.
An example would be great.

**Comment by zoechi** [comment]
I saw it mentioned that it's used for async actions. This is what I'm looking for how to register an action and how a reducer would look like.

**Comment by davidmarne** [comment]
First write a thunk
```dart
void myThunk(MiddlewareApi api) {
  var url = "http://my-server.com"; 
  // call the web server asynchronously.
  HttpRequest.getString(url).then(api.actions.onRequestResolved);
}
```

Then dispatch an action that has a payload of your thunk. Any action that has a payload that meets the Thunk typedef will be handled by the thunk middleware.

```dart
  store.actions.someAction(myThunk);
```

Note you have to add the thunk middleware to the list of middleware when instantiating your store.

Also, here is an example of an async action without using thunk
https://github.com/davidmarne/built_redux/issues/12

**Comment by zoechi** [comment]
great, thanks a lot!
