### ISSUE TITLE
is not working with Flutter dev channel

### ISSUE THREAD

**Issue by ralph-bergmann** [davidmarne/built_redux_thunk#6]
since a couple of days this is not working with the Flutter dev channel
When I switch back to Flutter beta it works

There is no error message or something else, it is just not working (thunk actions are not executed)

**Comment by davidmarne** [comment]
That's really weird. I'll try out the dev channel and see if I can reproduce.

**Comment by ralph-bergmann** [comment]
the problem, in my case, is that this test https://github.com/davidmarne/built_redux_thunk/blob/master/lib/src/built_redux_thunk.dart#L15 fails.

**Comment by davidmarne** [comment]
https://github.com/davidmarne/built_redux_thunk/releases/tag/0.5.0
is working for me now. sorry for the delay
